project:
  type: website

website:
  title: "Group 9"
  navbar:
    background: dark
    left:
    - href: overview.html
      text: Overview
    - href: method.html
      text: Methodology
    - href: findings.html
      text: Result & Discussion
    - href: lessons.html
      text: Lessons Learned
    - href: poster.html
      text: Poster
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About

format:
  html:
    theme: lux
    css: styles.css
    toc: true

editor: visual

