---
title: "Lessons Learned"
editor: visual
---

In order to improve the accuracy of classification, the training and testing samples have to be restricted to a smaller area size such that the sample is kept more pure to one specific land cover type. Needless to say, land cover change and land use change are intertwined, where local demand influences land use-land cover change. Punggol establishing itself as a new digital and ecotown has caught the attention of us, especially whilst coping to meet human demand and managing vegetation.

From our analysis, we can observe that Bare land, Built-up are inversely related with Managed vegetation. When the area of Bare land and Built-up increases, Managed vegetation decreases. This can be attributed to the upcoming developments in Punggol which resulted in deforestation of vegetation cover to make way for more residential and commercial developments. While this allows more land to be used for building more houses, wild green spaces such as forests and parks are being lost at the expense of human needs. 

Land cover change analysis may not achieve the desired accuracy as the spectral signature does not accurately distinguish between different types of area. A single pixel that is different to its surrounding pixels may not necessarily indicate that there is a different form of land type and some of the land area classification were found to be untrue by the team\'s manual checks. Avid checks have to be made before the team uses the data. In our project, we used the visible wavelength bands and near-infrared band to compose their spectral signature, but the drawbacks of using these bands is that the colour of a pixel would match to the most similar spectral signature, thus certain area has been misclassified to be water despite being in an enclosed dry land.
